[project]
name = "food-deals-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhiyi.chia", email = "zhiyi.chia@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
food-deals-mvp = "food_deals_mvp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
